### ISSUE TITLE
model does not work with preprocess: method: small

### ISSUE THREAD

**Issue by MathiasNT** [Essaim/CGCDemandPrediction#5]
Hi
Setting 
```
preprocess:
  hidden_size: 20
  method: small
```
in the evoconv2-config,yaml makes the model crash on line 273 in evonn2.py with error "tensors must be 2-D.

Am I missing another setting that needs to be changed?

**Comment by Essaim** [comment]
Hi, this is a leftover from the early experiments. It is useless. I have deleted it.

**Comment by MathiasNT** [comment]
Thanks!
Could you help me with the settings needed to reproduce the results from https://arxiv.org/pdf/2012.08080.pdf on the bike dataset?
